site_name: TREC Interactive Knowledge Assistance Track (iKAT)
site_url: https://www.ikat.com/
nav:
    - Home: index.md
    - Data: data.md
    - Guidelines: guidelines.md
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme: 
  name: material
  logo: logo.jpg
  palette:
     # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  analytics: 
    provider: google
    property: G-C0EGN6D7BM
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSfaceSg5cA0pXtq624Ii7evfz1uRDPyyXR4qclW1dCEMm5-2w/viewform?usp=sf_link" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/solid/envelope
      name: Email Us
      link: mailto:trec.ikat.ai@gmail.com
    - icon: fontawesome/brands/twitter
      name: Follow us on Twitter
      link: https://twitter.com/trec_ikat
    - icon: fontawesome/brands/slack
      name: Join the slack channel
      link: https://trectalk.slack.com/archives/C04QPBXNL01
    - icon: fontawesome/solid/user-group
      name: Join the Google group
      link: trec-ikat@googlegroups.com
copyright: Copyright &copy; 2023 TREC iKAT Organizers
